---
#     _    __                  _                                     _
#    | |  / /                 | |                                   | |
#    | | / /                  | |                                   | |
#    | |/ / _   _  ____   ____| | ______ ____   _____ ______   ____ | | __
#    | |\ \| | | |/ __ \ / __ \ |/ /  __/ __ \ / __  | _  _ \ / __ \| |/ /
#    | | \ \ \_| | <__> |  ___/   <| / | <__> | <__| | |\ |\ | <__> |   <
# By |_|  \_\__  |\___  |\____|_|\_\_|  \____^_\___  |_||_||_|\____^_\|\_\
#              | |    | |                          | |
#           ___/ | ___/ |                          | |
#          |____/ |____/                           |_|
#
# A PocketMine-MP plugin to see the server TPS and a player's ping
# Copyright (C) 2020-2021 Kygekraqmak, KygekTeam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# he Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

name: KygekPingTPS
version: 2.0.0-BETA
main: Kygekraqmak\KygekPingTPS\Main
api: 4.0.0
extensions:
  Core: ">=8.0"
authors: [Kygekraqmak, KygekTeam]

permissions:
  kygekpingtps.ping:
    description: Permission to use /ping
    default: true
  kygekpingtps.ping.others:
    default: op
  kygekpingtps.tps:
    description: Permission to use /tps
    default: true
...
