---
#
#  PLUGIN BY:
#   _    __                  _                                     _
#  | |  / /                 | |                                   | |
#  | | / /                  | |                                   | |
#  | |/ / _   _  ____   ____| | ______ ____   _____ ______   ____ | | __
#  | |\ \| | | |/ __ \ / __ \ |/ /  __/ __ \ / __  | _  _ \ / __ \| |/ /
#  | | \ \ \_| | <__> |  ___/   <| / | <__> | <__| | |\ |\ | <__> |   <
#  |_|  \_\__  |\___  |\____|_|\_\_|  \____^_\___  |_||_||_|\____^_\|\_\
#            | |    | |                          | |
#         ___/ | ___/ |                          | |
#        |____/ |____/                           |_|
#
# KygekPingTPS configuration file
#

# Prefix for all KygekPingTPS messages
# If empty, the plugin will use the default prefix
message.prefix: "&8[KygekPingTPS] "


# Messages configuration (Leave empty to use default messages)
# Use "&" as formatting codes
# Use "\n" to break into new line

# Use "{tps}" to display server TPS for /tps command
message.server-tps: "Current server TPS: &b{tps}"

# Use "{ping}" to display target player's ping for /ping command
# Use "{player}" to display the target player name
message.ping-self: "Your current ping: &b{ping}&rms."
message.ping-others: "{player}'s current ping: &b{ping}&rms."
message.player-not-found: "&cPlayer {player} was not found!"

# No permission messages
message.no-permission: "&cYou do not have permission to use this command!"
message.no-self-ping-perm: "&cYou do not have permission to see your ping!"
message.no-other-ping-perm: "&cYou do not have permission to see other player's ping!"


# Whether to check for plugin updates (Recommended)
check-updates: true

##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: "1.1"
#######################
...